[infra] check the setup.bash is called correctly when running tests on jenkins

diff --git a/scripts/continuous_integration/jenkins/test b/scripts/continuous_integration/jenkins/test
--- a/scripts/continuous_integration/jenkins/test
+++ b/scripts/continuous_integration/jenkins/test
@@ -31,7 +31,14 @@
 
 set -eo pipefail
 
-. install/setup.bash
+die() {
+    echo "$*" 1>&2
+    exit 1
+}
+
+. install/setup.bash || die "failed to find install/setup.bash $?"
+
+echo "DELPHYNE_RESOURCE_ROOT ....... $DELPHYNE_RESOURCE_ROOT"
 
 pushd build/delphyne
 CTEST_OUTPUT_ON_FAILURE=1 make test
